version: '3'
services:

  llm:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    networks:
      - net

  database:
    image: neo4j:enterprise
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=eval
    networks:
      - net

  loader:
    build:
      dockerfile: loader.Dockerfile

    environment:
      - NEO4J_URI=${NEO4J_URI-neo4j://database:7687}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD-password}
      - NEO4J_USERNAME=${NEO4J_USERNAME-neo4j}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - net
    depends_on:
      - database
      - llm

    ports:
      - 8081:8080

  bot:
    build:
      dockerfile: bot.Dockerfile

    environment:
      - NEO4J_URI=${NEO4J_URI-neo4j://database:7687}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD-password}
      - NEO4J_USERNAME=${NEO4J_USERNAME-neo4j}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - net
    depends_on:
      - database
      - llm
      - loader

    ports:
      - 8080:8080

networks:
  net:
